services:
  homepage-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: homepage-admin:0.5.3
    container_name: homepage-admin
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./example-config:/config
      - homepage-admin-dev-data:/data

volumes:
  homepage-admin-dev-data:
