services:
  homepage-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: homepage-admin:0.5.4
    container_name: homepage-admin
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "3001:3001"
    volumes:
      - ./example-config:/config
      - ./data:/data
